// my-react/src/App.jsx
/*
 * @Description: 
 * @Author: Wu Wei
 * @Date: 2024-04-13 17:43:39
 * @LastEditTime: 2024-04-17 16:00:43
 * @LastEditors: Wu Wei
 * @FilePath: \nodejs-basic\my-react\src\App.jsx
 */
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)
  const token = location.search.split("=")[1];
  fetch("http://localhost:3001/cors").then(res=>{
    console.log("测试跨域",res)
  })
  debugger
// if(!token){
//   fetch("http://localhost:3000/login?appId=9LQ8Y3mB").then(res=> {
//     debugger
//     location.href = res.url;
//   })
// }
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App

// my-vue/src/App.vue
<script setup>
// import HelloWorld from './components/HelloWorld.vue'
import Upload from "./views/Upload.vue"
// 登陆成功之后后端重定向的时候会携带token
// const token = location.search.split("=")[1];
// debugger
// if(!token){
//   fetch("http://localhost:3000/login?appId=Rs6s2aHi").then(res=>{
//     location.href = res.url;
//   })
// }
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <Upload />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
